"""Initial_db

Revision ID: 2ce78070e266
Revises: 
Create Date: 2024-01-31 00:20:21.218861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce78070e266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_discount_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('active_status', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ms_discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_id', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=150), nullable=True),
    sa.Column('nominal', sa.NUMERIC(precision=12), nullable=True),
    sa.Column('active_status', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['dt_id'], ['ms_discount_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ms_discount')
    op.drop_table('ms_discount_type')
    # ### end Alembic commands ###
